// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fxgsjefxexfiqbpdusph.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ4Z3NqZWZ4ZXhmaXFicGR1c3BoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyNjEyNjcsImV4cCI6MjA2NTgzNzI2N30.KLRuGsVO2LzDJT0SvBqs0L9M4Z7jGkCSrwNZ97LZ2pk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);